//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dmboar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public int id_register { get; set; }
        public int id_device { get; set; }
        public int id_user { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string permissions { get; set; }
    
        public virtual device device { get; set; }
        public virtual user user { get; set; }
    }
}
